AllCops:
  TargetRubyVersion: 2.4
  Include:
  - Rakefile
  Exclude:
  - tmp/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 130

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 25
  ExcludedMethods: [describe, context, let, it]

Style/BlockDelimiters:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Layout/IndentHash:
  EnforcedStyle: consistent

Style/WordArray:
  Enabled: true
